deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    # 1) See the files the runner has
    - name: List repo files
      run: |
        pwd
        ls -la

    # 2) Verify we can talk to AWS with your secrets..
    - name: Verify AWS identity and bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws --version
        aws sts get-caller-identity
        echo "Region: $AWS_REGION"
        echo "Bucket: ${{ secrets.AWS_S3_BUCKET }}"
        aws s3 ls "s3://${{ secrets.AWS_S3_BUCKET }}" || true

    # 3) Actual deploy (very explicit/verbose)
    - name: Sync to S3 with AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 sync . "s3://${{ secrets.AWS_S3_BUCKET }}" \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*"
        echo "----- After sync:"
        aws s3 ls "s3://${{ secrets.AWS_S3_BUCKET }}" --recursive
